### ISSUE TITLE
SpawnPoint

### ISSUE THREAD

**Issue by MikesDevAIAgent** [simpleC0de/save-position#1]
Plugin works fine, the problem is that the default server spawn point becomes whatever value you added in the sql file for "lastpos". Is there a way to change so the first time players spawn it doesn't go for the default value from the database?

**Comment by simpleC0de** [comment]
Go into the sql file, and change the values to your spawnpoint, that is the default spawn. 
If you already imported it, the simplest way is to delete and import it again with the new values; if you still need help, discord:
Peter Rameder#7548
