### ISSUE TITLE
Spielerposition konnte nicht geladen werden!

### ISSUE THREAD

**Issue by asil-ea** [simpleC0de/save-position#2]
I think i tried everything to fix the problem. mysql-async is up-to-date, plugin initializes after mysql-async. In the database, there is a row with player credentials, including lastpos but the plugin just doesn't work. any ideas?

**Comment by simpleC0de** [comment]
Any errors in the F8 console, or the server console?
If you want message me on Discord: Peter Rameder#7548

**Comment by asil-ea** [comment]
Thank you, i fixed it. The resource just couldn't reach to the database.

**Comment by ghost** [comment]
i have the same issue
No "Errors" only position can not be load
